package com.example.a302;

        import android.content.Context;
        import android.content.Intent;

        import androidx.core.content.ContextCompat;

        import java.util.ArrayList;
        import java.util.Arrays;

        import com.example.a302.Car;

public class DataProvider {

    static int[] carViews = {
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };

    static int[] carIds = {
            0, 1, 2, 3, 4, 5,6, 7, 8, 9, 10,
            11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
            21, 22, 23, 24, 25, 26, 27, 28, 29, 30
    };


    static String[] carNames = {
            "Audi E-tron 55 Advanced", "BMW i3 Rex Ranger", "BMW i3 rex ranger", "BMW i3 rex ranger", "Nissan Leaf", "Nissan Leaf 30s", "Nissan Leaf 24x", "Nissan Leaf", "Tesla Model S 75", "Tesla Model S P100DL", "Tesla Model S 75D",
            "Honda Fit", "Honda Fit","Honda Insight", "Mazda Axela HEV", "Toyota Aqua", "Toyota Aqua Camchain", "Toyota Camry", "Toyota Prius", "Toyota Prius", "Toyota Prius",
            "Nissan BlueBird Sylphy", "BMW 116i","BMW X1 18i S-Drive","Honda Accord Euro", "Lamborghini Gallardo", "Mazda 2 GSX", "Mazda Axele", "Mazda CX-5 GSX", "Toyota Aurion AT-X", "Toyota Corolla"
    };


    static String[] carMakes = {
            "Audi", "BMW", "BMW", "BMW", "Nissan", "Nissan", "Nissan", "Nissan", "Tesla", "Tesla", "Tesla",
            "Honda","Honda","Honda","Mazda","Toyota","Toyota","Toyota Camry","Toyota","Toyota","Toyota",
            "Nissan","BMW","BWM","Honda","Lamborghini","Mazda","Mazda","Mazda","Toyota","Toyota"
    };


    static String[] carYears = {
            "2019", "2014", "2015", "2016", "2016", "2015", "2017", "2018", "2017", "2018", "2019",
            "2011", "2015", "2014", "2014", "2012", "2015", "2015", "2011", "2013", "2014",
            "2014", "2013", "2011", "2004", "2016", "2020", "2010", "2019", "2012", "2017"
    };


    static String[] carDescriptions = {
            "With its combination of electric drive and a comfortable, sophisticated interior, the Audi e-tron creates a new sense of mobility. Whether parking, in the city or on long journeys, the Audi e-tron makes life easier for its driver in many situations. The full-size SUV combines sportiness and everyday practicality. Its two electric motors together with electric all-wheel drive provide for awesome performance and agile handling. The high-voltage battery is the foundation for a sufficient range. In combination with a comprehensive range of charging options for home and on the move, you can enjoy fully electric driving without having to compromise.",
            "The BMW i3 is a B-class, high-roof hatchback manufactured and marketed by BMW with an electric powertrain using rear wheel drive via a single-speed transmission and an underfloor Li-ion battery pack and an optional range-extending gasoline engine. The i3 was BMW's first mass-produced zero emissions vehicle and was launched as part of BMW's electric vehicle BMW i sub-brand.Styled by Richard Kim, the i3 uses a single five-door configuration with bodywork consisting of a passenger module of high strength, ultra-lightweight CFRP (carbon fiber reinforced plastic) glued to a lower aluminium module holding the chassis, battery, drive system and powertrain. The bodywork features two smaller clamshell rear-hinged rear doors. The i3 debuted as a concept at the 2011 International Motor Show Germany, and production began in September 2013[15] in Leipzig, German The i3 ranked third among all-electric cars sold worldwide from 2014 to 2016. Global sales since inception totaled more than 165,000 units at the beginning of 2020. The U.S. is its best-selling market with almost 42,000 units delivered through December 2019 The BMW i3 has won two World Car of the Year Awards, selected as 2014 World Green Car of the Year and also as 2014 World Car Design of the Year. The i3 received an iF Product Design Gold Award, and won both UK Car of the Year 2014 and Best Supermini of 2014 in the first UK Car of the Year Awards. It is reported that BMW has no plan for an i3 successor, as the company plans electrification of more models.",
            "The BMW i3 is a B-class, high-roof hatchback manufactured and marketed by BMW with an electric powertrain using rear wheel drive via a single-speed transmission and an underfloor Li-ion battery pack and an optional range-extending gasoline engine. The i3 was BMW's first mass-produced zero emissions vehicle and was launched as part of BMW's electric vehicle BMW i sub-brand.Styled by Richard Kim, the i3 uses a single five-door configuration with bodywork consisting of a passenger module of high strength, ultra-lightweight CFRP (carbon fiber reinforced plastic) glued to a lower aluminium module holding the chassis, battery, drive system and powertrain. The bodywork features two smaller clamshell rear-hinged rear doors. The i3 debuted as a concept at the 2011 International Motor Show Germany, and production began in September 2013[15] in Leipzig, German The i3 ranked third among all-electric cars sold worldwide from 2014 to 2016. Global sales since inception totaled more than 165,000 units at the beginning of 2020. The U.S. is its best-selling market with almost 42,000 units delivered through December 2019 The BMW i3 has won two World Car of the Year Awards, selected as 2014 World Green Car of the Year and also as 2014 World Car Design of the Year. The i3 received an iF Product Design Gold Award, and won both UK Car of the Year 2014 and Best Supermini of 2014 in the first UK Car of the Year Awards. It is reported that BMW has no plan for an i3 successor, as the company plans electrification of more models.",
            "The BMW i3 is a B-class, high-roof hatchback manufactured and marketed by BMW with an electric powertrain using rear wheel drive via a single-speed transmission and an underfloor Li-ion battery pack and an optional range-extending gasoline engine. The i3 was BMW's first mass-produced zero emissions vehicle and was launched as part of BMW's electric vehicle BMW i sub-brand.Styled by Richard Kim, the i3 uses a single five-door configuration with bodywork consisting of a passenger module of high strength, ultra-lightweight CFRP (carbon fiber reinforced plastic) glued to a lower aluminium module holding the chassis, battery, drive system and powertrain. The bodywork features two smaller clamshell rear-hinged rear doors. The i3 debuted as a concept at the 2011 International Motor Show Germany, and production began in September 2013[15] in Leipzig, German The i3 ranked third among all-electric cars sold worldwide from 2014 to 2016. Global sales since inception totaled more than 165,000 units at the beginning of 2020. The U.S. is its best-selling market with almost 42,000 units delivered through December 2019 The BMW i3 has won two World Car of the Year Awards, selected as 2014 World Green Car of the Year and also as 2014 World Car Design of the Year. The i3 received an iF Product Design Gold Award, and won both UK Car of the Year 2014 and Best Supermini of 2014 in the first UK Car of the Year Awards. It is reported that BMW has no plan for an i3 successor, as the company plans electrification of more models.",
            "The 2016 Nissan Leaf has a 107-horsepower electric motor that delivers decent acceleration for city driving, but falls short on the highway. The Leaf has a smooth ride over bumpy roads, and its handling around corners is composed. The base model can go up to 84 miles on a full charge, while higher trims can go up to 107 miles. The Leaf was a leader in driving range for electric vehicles (EVs) when it debuted in 2011, but other EVs have surpassed its range since then. The Nissan gets up to 114 mpg-e combined city/highway With the standard charger and a 110-volt outlet, you can fully charge the Leaf’s battery in 21 hours. You can cut charge time down to four hours by using a 240-volt outlet. The Leaf is also available with a fast-charge port, which can connect to some public charging stations to fill the battery to 80 percent in 30 minutes. The 2016 Leaf's cabin features unimpressive cheap plastics. However, the space feels roomy for a compact hatchback, and road visibility is excellent. You can easily find a comfortable driving position, and tall passengers will appreciate the abundant back-seat room. The Leaf has a long list of standard features, including a four-speaker stereo, Bluetooth, a USB port, satellite radio, push-button start, a rearview camera, hands-free text messaging, and the NissanConnect infotainment system with a 5-inch display and Nissan's Mobile Apps smartphone integration. Available features include a six-speaker stereo, a seven-speaker Bose audio system, HD Radio, navigation, a 360-degree camera, and the NissanConnect EV system, which allows you to use your smartphone to monitor the Leaf's charge.The Leaf's controls are easy to use, so you'll hardly have to look away from the road to adjust the radio station or air conditioning. The dashboard display shows you how much range you have left before you need to charge the batteries.There are two sets of lower anchors in the rear outboard seats and three top tethers for securing child seats. The Insurance Institute for Highway Safety gave the Leaf's LATCH system the second-lowest score of Marginal for ease of use.",
            "The 2016 Nissan Leaf has a 107-horsepower electric motor that delivers decent acceleration for city driving, but falls short on the highway. The Leaf has a smooth ride over bumpy roads, and its handling around corners is composed. The base model can go up to 84 miles on a full charge, while higher trims can go up to 107 miles. The Leaf was a leader in driving range for electric vehicles (EVs) when it debuted in 2011, but other EVs have surpassed its range since then. The Nissan gets up to 114 mpg-e combined city/highway With the standard charger and a 110-volt outlet, you can fully charge the Leaf’s battery in 21 hours. You can cut charge time down to four hours by using a 240-volt outlet. The Leaf is also available with a fast-charge port, which can connect to some public charging stations to fill the battery to 80 percent in 30 minutes. The 2016 Leaf's cabin features unimpressive cheap plastics. However, the space feels roomy for a compact hatchback, and road visibility is excellent. You can easily find a comfortable driving position, and tall passengers will appreciate the abundant back-seat room. The Leaf has a long list of standard features, including a four-speaker stereo, Bluetooth, a USB port, satellite radio, push-button start, a rearview camera, hands-free text messaging, and the NissanConnect infotainment system with a 5-inch display and Nissan's Mobile Apps smartphone integration. Available features include a six-speaker stereo, a seven-speaker Bose audio system, HD Radio, navigation, a 360-degree camera, and the NissanConnect EV system, which allows you to use your smartphone to monitor the Leaf's charge.The Leaf's controls are easy to use, so you'll hardly have to look away from the road to adjust the radio station or air conditioning. The dashboard display shows you how much range you have left before you need to charge the batteries.There are two sets of lower anchors in the rear outboard seats and three top tethers for securing child seats. The Insurance Institute for Highway Safety gave the Leaf's LATCH system the second-lowest score of Marginal for ease of use.",
            "The 2016 Nissan Leaf has a 107-horsepower electric motor that delivers decent acceleration for city driving, but falls short on the highway. The Leaf has a smooth ride over bumpy roads, and its handling around corners is composed. The base model can go up to 84 miles on a full charge, while higher trims can go up to 107 miles. The Leaf was a leader in driving range for electric vehicles (EVs) when it debuted in 2011, but other EVs have surpassed its range since then. The Nissan gets up to 114 mpg-e combined city/highway With the standard charger and a 110-volt outlet, you can fully charge the Leaf’s battery in 21 hours. You can cut charge time down to four hours by using a 240-volt outlet. The Leaf is also available with a fast-charge port, which can connect to some public charging stations to fill the battery to 80 percent in 30 minutes. The 2016 Leaf's cabin features unimpressive cheap plastics. However, the space feels roomy for a compact hatchback, and road visibility is excellent. You can easily find a comfortable driving position, and tall passengers will appreciate the abundant back-seat room. The Leaf has a long list of standard features, including a four-speaker stereo, Bluetooth, a USB port, satellite radio, push-button start, a rearview camera, hands-free text messaging, and the NissanConnect infotainment system with a 5-inch display and Nissan's Mobile Apps smartphone integration. Available features include a six-speaker stereo, a seven-speaker Bose audio system, HD Radio, navigation, a 360-degree camera, and the NissanConnect EV system, which allows you to use your smartphone to monitor the Leaf's charge.The Leaf's controls are easy to use, so you'll hardly have to look away from the road to adjust the radio station or air conditioning. The dashboard display shows you how much range you have left before you need to charge the batteries.There are two sets of lower anchors in the rear outboard seats and three top tethers for securing child seats. The Insurance Institute for Highway Safety gave the Leaf's LATCH system the second-lowest score of Marginal for ease of use.",
            "The 2016 Nissan Leaf has a 107-horsepower electric motor that delivers decent acceleration for city driving, but falls short on the highway. The Leaf has a smooth ride over bumpy roads, and its handling around corners is composed. The base model can go up to 84 miles on a full charge, while higher trims can go up to 107 miles. The Leaf was a leader in driving range for electric vehicles (EVs) when it debuted in 2011, but other EVs have surpassed its range since then. The Nissan gets up to 114 mpg-e combined city/highway With the standard charger and a 110-volt outlet, you can fully charge the Leaf’s battery in 21 hours. You can cut charge time down to four hours by using a 240-volt outlet. The Leaf is also available with a fast-charge port, which can connect to some public charging stations to fill the battery to 80 percent in 30 minutes. The 2016 Leaf's cabin features unimpressive cheap plastics. However, the space feels roomy for a compact hatchback, and road visibility is excellent. You can easily find a comfortable driving position, and tall passengers will appreciate the abundant back-seat room. The Leaf has a long list of standard features, including a four-speaker stereo, Bluetooth, a USB port, satellite radio, push-button start, a rearview camera, hands-free text messaging, and the NissanConnect infotainment system with a 5-inch display and Nissan's Mobile Apps smartphone integration. Available features include a six-speaker stereo, a seven-speaker Bose audio system, HD Radio, navigation, a 360-degree camera, and the NissanConnect EV system, which allows you to use your smartphone to monitor the Leaf's charge.The Leaf's controls are easy to use, so you'll hardly have to look away from the road to adjust the radio station or air conditioning. The dashboard display shows you how much range you have left before you need to charge the batteries.There are two sets of lower anchors in the rear outboard seats and three top tethers for securing child seats. The Insurance Institute for Highway Safety gave the Leaf's LATCH system the second-lowest score of Marginal for ease of use.",
            "The Tesla Model S is an all-electric five-door liftback sedan, produced by Tesla, Inc. and introduced on June 22, 2012. As of March 2020, the Model S Long Range Plus han EPA range of 390 miles (630 km), higher than that of any other battery electric car.Model S cars built from October 2014 have a feature called Autopilot, an advanced driver assistance system that allows the car to operate without assistance from the driver However, the driver must supervise continuously and take control if there is an issue. Autopilot 2.0, introduced in October 2016, also includes Enhanced Summon, which allows the car to navigate through a parking lot to its owner without anyone in the driver's seat. Sentry mode, available on cars built after August 2017, senses and records suspicious activity around the car.In 2013, the Model S became the first electric car to top the monthly new-car-sales ranking in any country, twice leading in Norway, in September and December 2013 and also in Denmark in December 2015.[20] Global Model S sales passed 250,000 units in September 2018 (more recent numbers are not available because Tesla combines sales of Model S and Model X). The U.S. is its leading market, with about 158,000 units delivered through December 2019. The Tesla Model S was the top-selling plug-in electric car worldwide in 2015 and 2016.The December 2017 Consumer Reports owner satisfaction survey had the Tesla Model S at the top for all cars; in December 2019, it's in fifth position. In 2019, the US magazine Motor Trend named the 2013 Tesla Model S the ultimate car of the year over the magazine's 70-year history.",
            "The Tesla Model S is an all-electric five-door liftback sedan, produced by Tesla, Inc. and introduced on June 22, 2012. As of March 2020, the Model S Long Range Plus han EPA range of 390 miles (630 km), higher than that of any other battery electric car.Model S cars built from October 2014 have a feature called Autopilot, an advanced driver assistance system that allows the car to operate without assistance from the driver However, the driver must supervise continuously and take control if there is an issue. Autopilot 2.0, introduced in October 2016, also includes Enhanced Summon, which allows the car to navigate through a parking lot to its owner without anyone in the driver's seat. Sentry mode, available on cars built after August 2017, senses and records suspicious activity around the car.In 2013, the Model S became the first electric car to top the monthly new-car-sales ranking in any country, twice leading in Norway, in September and December 2013 and also in Denmark in December 2015.[20] Global Model S sales passed 250,000 units in September 2018 (more recent numbers are not available because Tesla combines sales of Model S and Model X). The U.S. is its leading market, with about 158,000 units delivered through December 2019. The Tesla Model S was the top-selling plug-in electric car worldwide in 2015 and 2016.The December 2017 Consumer Reports owner satisfaction survey had the Tesla Model S at the top for all cars; in December 2019, it's in fifth position. In 2019, the US magazine Motor Trend named the 2013 Tesla Model S the ultimate car of the year over the magazine's 70-year history.",
            "The Tesla Model S is an all-electric five-door liftback sedan, produced by Tesla, Inc. and introduced on June 22, 2012. As of March 2020, the Model S Long Range Plus han EPA range of 390 miles (630 km), higher than that of any other battery electric car.Model S cars built from October 2014 have a feature called Autopilot, an advanced driver assistance system that allows the car to operate without assistance from the driver However, the driver must supervise continuously and take control if there is an issue. Autopilot 2.0, introduced in October 2016, also includes Enhanced Summon, which allows the car to navigate through a parking lot to its owner without anyone in the driver's seat. Sentry mode, available on cars built after August 2017, senses and records suspicious activity around the car.In 2013, the Model S became the first electric car to top the monthly new-car-sales ranking in any country, twice leading in Norway, in September and December 2013 and also in Denmark in December 2015.[20] Global Model S sales passed 250,000 units in September 2018 (more recent numbers are not available because Tesla combines sales of Model S and Model X). The U.S. is its leading market, with about 158,000 units delivered through December 2019. The Tesla Model S was the top-selling plug-in electric car worldwide in 2015 and 2016.The December 2017 Consumer Reports owner satisfaction survey had the Tesla Model S at the top for all cars; in December 2019, it's in fifth position. In 2019, the US magazine Motor Trend named the 2013 Tesla Model S the ultimate car of the year over the magazine's 70-year history.",

            "The Honda Fit (Japanese: ホンダ・フィット, Hepburn: Honda Fitto), also marketed as the Honda Jazz, is a five-door B-segment supermini manufactured and marketed by Honda since 2001 and now in its fourth generation. Marketed worldwide and manufactured at ten plants in eight countries, sales reached almost 5 million by mid-2013.Sharing Honda's global small car platform with the City, Airwave, first generation Mobilio and Freed, the Fit is noted for its one-box or monospace design and its re-configurable interior—with a cargo volume competitive to larger vehicles.Honda released hybrid petroleum-electric versions of the Fit in Japan in October 2010 and in Europe in early 2011.Honda released the Fit EV, a limited production all-electric version, in the United States in July 2012 and in Japan the following month. By 2012, Honda Fit was produced in 12 countries, including Japan, Brazil, China, India and Indonesia.Honda uses the \"Jazz\" nameplate in Europe, Oceania, the Middle East, Africa, Hong Kong, Macau, some ASEAN countries and India; and \"Fit\" in Japan, Sri Lanka, China, Taiwan and the Americas.",
            "The Honda Fit (Japanese: ホンダ・フィット, Hepburn: Honda Fitto), also marketed as the Honda Jazz, is a five-door B-segment supermini manufactured and marketed by Honda since 2001 and now in its fourth generation. Marketed worldwide and manufactured at ten plants in eight countries, sales reached almost 5 million by mid-2013.Sharing Honda's global small car platform with the City, Airwave, first generation Mobilio and Freed, the Fit is noted for its one-box or monospace design and its re-configurable interior—with a cargo volume competitive to larger vehicles.Honda released hybrid petroleum-electric versions of the Fit in Japan in October 2010 and in Europe in early 2011.Honda released the Fit EV, a limited production all-electric version, in the United States in July 2012 and in Japan the following month. By 2012, Honda Fit was produced in 12 countries, including Japan, Brazil, China, India and Indonesia.Honda uses the \"Jazz\" nameplate in Europe, Oceania, the Middle East, Africa, Hong Kong, Macau, some ASEAN countries and India; and \"Fit\" in Japan, Sri Lanka, China, Taiwan and the Americas.",
            "The Honda Insight (Japanese: ホンダ・インサイト, Honda Insaito) is a hybrid electric vehicle that was manufactured and marketed by Honda in its first generation as a two-door, two passenger liftback (1999–2006) and in its second generation as a four-door, five passenger liftback (2009–2014). In its third generation, it became a four-door sedan (2019–present). It was Honda's first model with Integrated Motor Assist system and the most fuel efficient gasoline-powered car available in the U.S. without plug-in capability — for the length of its production run.EPA estimates for the first-generation Insight were 61 City/70 Highway/65 Combined, under then-current EPA standards. Subsequent EPA standards reduced the estimates to 49 City/61 Highway/53 Combined.Honda introduced the second-generation Insight in Japan in February 2009 and in the United States on March 24, 2009. The Insight was the least expensive hybrid available in the US. In December 2010, Honda introduced a less expensive base model for the 2011 model year. The Insight was launched April 2009 in the UK as the lowest priced hybrid on the market and became the best selling hybrid for the month. The Insight ranked as the top-selling vehicle in Japan for the month of April 2009, a first for a hybrid model. During its first twelve months after first available in the Japanese market, the second-generation Insight sold 143,015 units around the world.In July 2014 Honda announced the end of production of the Insight for the 2015 model, together with the Honda FCX Clarity hydrogen fuel-cell car and the Honda Fit EV electric car.",
            "The 2012 Mazda3 with SkyActiv powertrain was unveiled at the Canadian International Auto Show in Toronto, February 2011. It comes with Mazda's SkyActiv-G 2.0-liter, direct-injection gasoline engine, and SkyActiv-Drive 6-speed automatic or SkyActiv-MT 6-speed manual transmission. There are minor exterior updates: revised grille and air intakes, and a reshaped rear valance panel. Skyactiv models receive a blue ring around the projectors in the headlamps. Car and Driver reported that such a Mazda3 can reach estimated EPA fuel-economy ratings of 30 mpg city and 39 to 40 highway.",
            "The Toyota Prius c (c stands for city), named the Toyota Aqua (aqua is Latin for water) in Japan, is a full hybrid gasoline-electric subcompact/supermini hatchback manufactured and marketed by Toyota Motor Corporation. The Prius c is the third member of the Prius family, and combines the features of a Yaris-sized car with a hybrid powertrain. The Prius c is priced lower than the conventional Prius and has a higher fuel economy in city driving under United States Environmental Protection Agency test cycles.The Prius c was ranked by the EPA as the 2012 most fuel efficient compact car when plug-in electric vehicles are excluded.The production version of the Aqua was unveiled in the 2011 Tokyo Motor Show. The production Prius c was introduced in the U.S. at the January 2012 North American International Auto Show in Detroit. The Aqua was launched in Japan in December 2011 at a price of ¥1.69 million (US$21,700). Sales in several Asian markets began in January 2012. The Prius c was released in the U.S. and Canada in March 2012. Sales in Australia and New Zealand began in April 2012.The Aqua is considered the most successful nameplate launch in Japan in the last 20 years. As of January 2017, the Aqua/Prius c is the second most sold hybrid of Toyota Motor Corporation after the regular Prius, with 1,380,100 units sold worldwide. Japan as the market leader with 1,154,500 units sold through January 2017. The Aqua was the top selling new car in Japan for three years in a row, from 2013 to 2015.The Prius C was discontinued in United States at the end of the 2019 model year. Sales continued in other parts of the world. With the introduction of the Yaris Hybrid, the Prius c was discontinued in Australia in early 2020.",
            "The Toyota Prius c (c stands for city), named the Toyota Aqua (aqua is Latin for water) in Japan, is a full hybrid gasoline-electric subcompact/supermini hatchback manufactured and marketed by Toyota Motor Corporation. The Prius c is the third member of the Prius family, and combines the features of a Yaris-sized car with a hybrid powertrain. The Prius c is priced lower than the conventional Prius and has a higher fuel economy in city driving under United States Environmental Protection Agency test cycles.The Prius c was ranked by the EPA as the 2012 most fuel efficient compact car when plug-in electric vehicles are excluded.The production version of the Aqua was unveiled in the 2011 Tokyo Motor Show. The production Prius c was introduced in the U.S. at the January 2012 North American International Auto Show in Detroit. The Aqua was launched in Japan in December 2011 at a price of ¥1.69 million (US$21,700). Sales in several Asian markets began in January 2012. The Prius c was released in the U.S. and Canada in March 2012. Sales in Australia and New Zealand began in April 2012.The Aqua is considered the most successful nameplate launch in Japan in the last 20 years. As of January 2017, the Aqua/Prius c is the second most sold hybrid of Toyota Motor Corporation after the regular Prius, with 1,380,100 units sold worldwide. Japan as the market leader with 1,154,500 units sold through January 2017. The Aqua was the top selling new car in Japan for three years in a row, from 2013 to 2015.The Prius C was discontinued in United States at the end of the 2019 model year. Sales continued in other parts of the world. With the introduction of the Yaris Hybrid, the Prius c was discontinued in Australia in early 2020.",
            "The Toyota Prius c (c stands for city), named the Toyota Aqua (aqua is Latin for water) in Japan, is a full hybrid gasoline-electric subcompact/supermini hatchback manufactured and marketed by Toyota Motor Corporation. The Prius c is the third member of the Prius family, and combines the features of a Yaris-sized car with a hybrid powertrain. The Prius c is priced lower than the conventional Prius and has a higher fuel economy in city driving under United States Environmental Protection Agency test cycles.The Prius c was ranked by the EPA as the 2012 most fuel efficient compact car when plug-in electric vehicles are excluded.The production version of the Aqua was unveiled in the 2011 Tokyo Motor Show. The production Prius c was introduced in the U.S. at the January 2012 North American International Auto Show in Detroit. The Aqua was launched in Japan in December 2011 at a price of ¥1.69 million (US$21,700). Sales in several Asian markets began in January 2012. The Prius c was released in the U.S. and Canada in March 2012. Sales in Australia and New Zealand began in April 2012.The Aqua is considered the most successful nameplate launch in Japan in the last 20 years. As of January 2017, the Aqua/Prius c is the second most sold hybrid of Toyota Motor Corporation after the regular Prius, with 1,380,100 units sold worldwide. Japan as the market leader with 1,154,500 units sold through January 2017. The Aqua was the top selling new car in Japan for three years in a row, from 2013 to 2015.The Prius C was discontinued in United States at the end of the 2019 model year. Sales continued in other parts of the world. With the introduction of the Yaris Hybrid, the Prius c was discontinued in Australia in early 2020.",
            "The Toyota Prius c (c stands for city), named the Toyota Aqua (aqua is Latin for water) in Japan, is a full hybrid gasoline-electric subcompact/supermini hatchback manufactured and marketed by Toyota Motor Corporation. The Prius c is the third member of the Prius family, and combines the features of a Yaris-sized car with a hybrid powertrain. The Prius c is priced lower than the conventional Prius and has a higher fuel economy in city driving under United States Environmental Protection Agency test cycles.The Prius c was ranked by the EPA as the 2012 most fuel efficient compact car when plug-in electric vehicles are excluded.The production version of the Aqua was unveiled in the 2011 Tokyo Motor Show. The production Prius c was introduced in the U.S. at the January 2012 North American International Auto Show in Detroit. The Aqua was launched in Japan in December 2011 at a price of ¥1.69 million (US$21,700). Sales in several Asian markets began in January 2012. The Prius c was released in the U.S. and Canada in March 2012. Sales in Australia and New Zealand began in April 2012.The Aqua is considered the most successful nameplate launch in Japan in the last 20 years. As of January 2017, the Aqua/Prius c is the second most sold hybrid of Toyota Motor Corporation after the regular Prius, with 1,380,100 units sold worldwide. Japan as the market leader with 1,154,500 units sold through January 2017. The Aqua was the top selling new car in Japan for three years in a row, from 2013 to 2015.The Prius C was discontinued in United States at the end of the 2019 model year. Sales continued in other parts of the world. With the introduction of the Yaris Hybrid, the Prius c was discontinued in Australia in early 2020.",
            "The Toyota Prius c (c stands for city), named the Toyota Aqua (aqua is Latin for water) in Japan, is a full hybrid gasoline-electric subcompact/supermini hatchback manufactured and marketed by Toyota Motor Corporation. The Prius c is the third member of the Prius family, and combines the features of a Yaris-sized car with a hybrid powertrain. The Prius c is priced lower than the conventional Prius and has a higher fuel economy in city driving under United States Environmental Protection Agency test cycles.The Prius c was ranked by the EPA as the 2012 most fuel efficient compact car when plug-in electric vehicles are excluded.The production version of the Aqua was unveiled in the 2011 Tokyo Motor Show. The production Prius c was introduced in the U.S. at the January 2012 North American International Auto Show in Detroit. The Aqua was launched in Japan in December 2011 at a price of ¥1.69 million (US$21,700). Sales in several Asian markets began in January 2012. The Prius c was released in the U.S. and Canada in March 2012. Sales in Australia and New Zealand began in April 2012.The Aqua is considered the most successful nameplate launch in Japan in the last 20 years. As of January 2017, the Aqua/Prius c is the second most sold hybrid of Toyota Motor Corporation after the regular Prius, with 1,380,100 units sold worldwide. Japan as the market leader with 1,154,500 units sold through January 2017. The Aqua was the top selling new car in Japan for three years in a row, from 2013 to 2015.The Prius C was discontinued in United States at the end of the 2019 model year. Sales continued in other parts of the world. With the introduction of the Yaris Hybrid, the Prius c was discontinued in Australia in early 2020.",
            "The Toyota Prius c (c stands for city), named the Toyota Aqua (aqua is Latin for water) in Japan, is a full hybrid gasoline-electric subcompact/supermini hatchback manufactured and marketed by Toyota Motor Corporation. The Prius c is the third member of the Prius family, and combines the features of a Yaris-sized car with a hybrid powertrain. The Prius c is priced lower than the conventional Prius and has a higher fuel economy in city driving under United States Environmental Protection Agency test cycles.The Prius c was ranked by the EPA as the 2012 most fuel efficient compact car when plug-in electric vehicles are excluded.The production version of the Aqua was unveiled in the 2011 Tokyo Motor Show. The production Prius c was introduced in the U.S. at the January 2012 North American International Auto Show in Detroit. The Aqua was launched in Japan in December 2011 at a price of ¥1.69 million (US$21,700). Sales in several Asian markets began in January 2012. The Prius c was released in the U.S. and Canada in March 2012. Sales in Australia and New Zealand began in April 2012.The Aqua is considered the most successful nameplate launch in Japan in the last 20 years. As of January 2017, the Aqua/Prius c is the second most sold hybrid of Toyota Motor Corporation after the regular Prius, with 1,380,100 units sold worldwide. Japan as the market leader with 1,154,500 units sold through January 2017. The Aqua was the top selling new car in Japan for three years in a row, from 2013 to 2015.The Prius C was discontinued in United States at the end of the 2019 model year. Sales continued in other parts of the world. With the introduction of the Yaris Hybrid, the Prius c was discontinued in Australia in early 2020.",

            " The Nissan Bluebird is a compact car with a model name introduced in 1957. It has been Nissan's most internationally recognized sedan, in multiple body styles, and is known for its dependability and durability. The Bluebird originated from Nissan's first vehicles, dating to the early 1900s, and its traditional competitor became the Toyota Corona. The Bluebird was positioned to compete with the Corona, as the Corona was developed to continue offering a sedan used as a taxi since Toyota Crown was growing in size. Every generation of the Bluebird has been available as a taxi, duties that are shared with base level Nissan Cedrics. It is one of the longest-running nameplates from a Japanese automaker. It spawned most of Nissan's products sold internationally, and has been known by a number of different names and bodystyles, including the 160J/710/Violet/Auster/Stanza line.",
            " The BMW 1 Series is a range of subcompact executive cars (C-segment) manufactured by BMW since 2004. It is the successor to the BMW 3 Series Compact and is currently in its third generation.The first generation was produced in hatchback, coupe and convertible body styles. Since the second generation (introduced in 2013), the coupé and convertible models have been marketed as the 2 Series, therefore the 1 Series range no longer includes these body styles. A sedan model became available for the Chinese market in 2017.The 1 Series is BMW's entry level of model range. Unusually for a small car, the 1 Series range is mostly rear-wheel drive, (except for the F52 sedan, which is front-wheel drive) with optional all-wheel drive being available on some models.An M version was produced for the first generation: the BMW 1 Series M Coupe, which was succeeded by the BMW M2.",
            " The BMW 1 Series is a range of subcompact executive cars (C-segment) manufactured by BMW since 2004. It is the successor to the BMW 3 Series Compact and is currently in its third generation.The first generation was produced in hatchback, coupe and convertible body styles. Since the second generation (introduced in 2013), the coupé and convertible models have been marketed as the 2 Series, therefore the 1 Series range no longer includes these body styles. A sedan model became available for the Chinese market in 2017.The 1 Series is BMW's entry level of model range. Unusually for a small car, the 1 Series range is mostly rear-wheel drive, (except for the F52 sedan, which is front-wheel drive) with optional all-wheel drive being available on some models.An M version was produced for the first generation: the BMW 1 Series M Coupe, which was succeeded by the BMW M2.",
            " The Honda Accord (Japanese: ホンダ・アコード, Honda Akōdo) /əˈkɔːrd/ is a series of automobiles manufactured by Honda since 1976, best known for its four-door sedan variant, which has been one of the best-selling cars in the United States since 1989. The Accord nameplate has been applied to a variety of vehicles worldwide, including coupes, station wagons, hatchbacks and a Honda Crosstour crossover.Since initiation, Honda has offered several different car body styles and versions of the Accord, and often vehicles marketed under the Accord nameplate concurrently in different regions differ quite substantially. It debuted in 1976, as a compact hatchback, though this style only lasted through 1989, as the lineup was expanded to include a sedan, coupe and wagon. By the sixth-generation Accord at the end of the 1990s, it evolved into an intermediate vehicle, with one basic platform but with different bodies and proportions to increase its competitiveness against its rivals in different international markets. For the eighth-generation Accord released for the North American market in 2007, Honda had again chosen to move the model further upscale and increase its size.This pushed the Accord sedan from the upper limit of what the U.S. Environmental Protection Agency (EPA) defines as a mid-size car to just above the lower limit of a full-size car, with the coupe still rated as a mid-size car. In 2012, the ninth-generation Accord sedan, with smaller exterior dimensions, was once again classified as a mid-size car at 119 cubic feet (3.4 m3), falling just shy of the Large Car classification. However, the tenth-generation Accord sedan, with similar exterior dimensions, returned to full-size car status with its combined interior space of 123 cubic feet (3.5 m3); the coupe was discontinued in 2017.In 1982, the Accord became the first car from a Japanese manufacturer to be produced in the United States when production commenced in Marysville, Ohio at Honda's Marysville Auto Plant. The Accord has achieved considerable success, especially in the United States, where it was the best-selling Japanese car for sixteen years (1982–97), topping its class in sales in 1991 and 2001, with around ten million vehicles sold. Numerous road tests, past and present, rate the Accord as one of the world's most reliable vehicles. The Accord has been on the Car and Driver 10Best list a record 30 times.In 1989, the Accord was the first vehicle sold under an import brand to become the best-selling automobile in the United States.",
            " The Lamborghini Gallardo (/ɡaɪˈjɑːrdoʊ/; Spanish: [ɡaˈʎaɾðo]) is a sports car built by the Italian automotive manufacturer Lamborghini from 2003 to 2013. It is Lamborghini's best-selling model with 14,022 built throughout its production run.[7] Named after a famous breed of fighting bull,[8] the V10 powered Gallardo has been Lamborghini's sales leader and stable-mate to a succession of V12 flagship models—first to the Murciélago (4,099 built between 2001 and 2010), then to the current flagship, the Aventador. On 25 November 2013, the last Gallardo was rolled off the production line. The Gallardo was replaced by the Huracán in 2014.",
            " The Mazda Demio is a supermini manufactured and marketed globally by Mazda since 1996, currently in its fourth generation. The Demio is marketed prominently as the Mazda2 and under previous nameplates including Mazda 121, Mazda Metro and Ford Festiva Mini Wagon.The third generation Demio earned the 2008 World Car of the Year title, while the fourth generation was awarded the 2014–2015 Japanese Car of the Year.In Canada, Mexico and the United States, the Demio was sold by Toyota with slight styling changes as an iteration of the Toyota Yaris sedan. In the United States, it was initially marketed under Toyota's youth-oriented Scion brand as the Scion iA. For the 2017 model year, it was re-branded as the Toyota Yaris iA due to the discontinuation of the Scion marque. For the 2019 model year, the iA moniker was dropped.Presently, the Mazda2 is available in Canada and Mexico, but not the United States except Puerto Rico. For the 2020 model year, the Demio-based Toyota Yaris hatchback is also available in the United States and Canada.Originating with the introduction of the Mazda 121 in 1987, this B-segment small car was based on the Mazda D-platform. Ford also used a version of the first-generation DA 121 known as the Ford Festiva. Mazda later released the Autozam Revue in 1990 with the next generation of the D-platform DB. It was redesigned for January 1993, still based on the same DB platform. Kia also built versions of the DA and DB, both for itself and for Ford's sale as the Ford Aspire in the United States which Kia sold as the Pride and Avella. The name Demio is derived from Latin meus to show possession, which in many Romance languages has become mio. The Demio nameplate was discontinued in all remaining markets in September 2019, and replaced by the Mazda2 moniker worldwide.",
            " The Mazda 3 (known as the Mazda Axela in Japan (first three generations), a combination of accelerate and excellent) is a compact car manufactured in Japan by Mazda. It was introduced in 2003 as a 2004 model, replacing the Familia/323/Protegé in the C-segment. A performance-oriented version of the Mazda3 was marketed as the Mazdaspeed3 in North America, Axela in Japan, and the Mazda 3 MPS in Europe.A second-generation Mazda 3 for the 2009 model year was unveiled in late 2008, with the sedan premièring at the Los Angeles Auto Show and the hatchback at the Bologna Motor Show. For the 2012 model year, Mazda began offering the Mazda 3 with their newly-developed SkyActiv technology, including a more rigid body, a new direct-injection engine, and a new 6-speed transmission.The third generation was introduced in mid-2013 as a 2014 model.A fourth-generation Mazda 3 for the 2019 model year was unveiled in November 2018 at the Los Angeles Auto Show and the ASEAN premiere at the Singapore Motor Show. For the 2019 model, the all-new Mazda3 is equipped with the newly-developed SkyActiv technology, including the latest SkyActiv-X, SkyActiv-G and SkyActiv-D engines, each of which provides responsive speed control in any driving situation, and a Spark-Controlled Compression Ignition system.The Mazda3 became Mazda's fastest-selling vehicle in January 2019, with cumulative sales of over 6 million units.",
            " The second generation CX-5 was unveiled with an overhauled design and new tech on November 15, 2016 at the Los Angeles Auto Show.The CX-5 is available with SKYACTIV-G 2.0 gasoline, SKYACTIV-G 2.5 gasoline and SKYACTIV-D 2.2 diesel engines. New features include a new 'Soul Red Crystal' body color as well as a new remote controlled powered tailgate.The 2019 CX-5 adds the CX-9 engine as an option. The Skyactiv-G 2.5-liter turbocharged four-cylinder produces 250 horsepower at 5,000 rpm on 93-octane fuel and 227 hp on 87-octane. Mazda claims the new engine delivers 22 mpg city, 27 highway, and 24 mpg combined in AWD trim regardless of octane",
            " The Toyota Aurion /ˈɔːriən/ is a mid-size car produced by Toyota in Australia and parts of Asia from 2006 to 2017. In the two generations it was produced, the Aurion was derived from the equivalent Toyota Camry. Changes were mainly limited to revised front- and rear-end treatment, along with changes to the interior. The Camry-based Aurion was also sold in the majority of East and Southeast Asia as the Toyota Camry, with the original version of the Camry sold alongside the Aurion in Australasia and the Middle East. In the previous two markets, the car replaced the Avalon model, which can trace its roots back to the early 1990s. A total of 111,140 Aurion's were sold over the 10 year Australian production span.",
            " The Toyota Corolla (Japanese: トヨタ・カローラ, Toyota Karōra) is a line of subcompact and compact cars manufactured by Toyota. Introduced in 1966, the Corolla was the best-selling car worldwide by 1974 and has been one of the best-selling cars in the world since then. In 1997, the Corolla became the best selling nameplate in the world, surpassing the Volkswagen Beetle. Toyota reached the milestone of 44 million Corollas sold over twelve generations in 2016. The series has undergone several major redesigns.The name Corolla is part of Toyota's naming tradition of using names derived from the Toyota Crown for sedans, with corolla Latin for small crown.The Corolla has always been exclusive in Japan to Toyota Corolla Store locations, and manufactured in Japan with a twin, called the Toyota Sprinter until 2000. From 2006 to 2018 in Japan and much of the world, and since 2018 in Taiwan, the hatchback companion has been called the Toyota Auris.Early models were mostly rear-wheel drive, while later models have been front-wheel drive. Four-wheel drive versions have also been produced. The Corolla's traditional competitors have been the Nissan Sunny, introduced the same year as the Corolla in Japan and the later Honda Civic and Mitsubishi Lancer. The Corolla's chassis designation code is E, as described in Toyota's chassis and engine codes.",
    };


    static int[][] carImages = {
            {R.drawable.audi201911, R.drawable.audi201912, R.drawable.audi201913,},
            {R.drawable.bmw201411, R.drawable.bmw201412, R.drawable.bmw201413},
            {R.drawable.bmw201511, R.drawable.bmw201512, R.drawable.bmw201513},
            {R.drawable.bmw201611, R.drawable.bmw201612, R.drawable.bmw201613},
            {R.drawable.nissan201611, R.drawable.nissan201612, R.drawable.nissan201613},
            {R.drawable.nissan201511, R.drawable.nissan201512, R.drawable.nissan201513},
            {R.drawable.nissan201711, R.drawable.nissan201712, R.drawable.nissan201713},
            {R.drawable.nissan201811, R.drawable.nissan201812, R.drawable.nissan201813},
            {R.drawable.tesla201711, R.drawable.tesla201712, R.drawable.tesla201713},
            {R.drawable.telsa201811, R.drawable.telsa201812, R.drawable.telsa201813},
            {R.drawable.tesla201911, R.drawable.tesla201912, R.drawable.tesla201913},
            {R.drawable.honda201121, R.drawable.honda201122, R.drawable.honda201123},
            {R.drawable.honda201521, R.drawable.honda201522, R.drawable.honda201523},
            {R.drawable.honda201421, R.drawable.honda201422, R.drawable.honda201423},
            {R.drawable.mazda201421, R.drawable.mazda201422, R.drawable.mazda201423},
            {R.drawable.toyota201221, R.drawable.toyota201222, R.drawable.toyota201223},
            {R.drawable.toyota201521, R.drawable.toyota201522, R.drawable.toyota201523},
            {R.drawable.toyotacamry201521, R.drawable.toyotacamry201522, R.drawable.toyotacamry201523},
            {R.drawable.toyota201121, R.drawable.toyota201122, R.drawable.toyota201123},
            {R.drawable.toyota201321, R.drawable.toyota201322, R.drawable.toyota201323},
            {R.drawable.toyota201422, R.drawable.toyota201422, R.drawable.toyota201423},
            {R.drawable.nissan201431, R.drawable.nissan201432, R.drawable.nissan201433},
            {R.drawable.bmw201331, R.drawable.bmw201332, R.drawable.bmw201333},
            {R.drawable.bmw201131, R.drawable.bmw201132, R.drawable.bmw201133},
            {R.drawable.honda200431, R.drawable.honda200432, R.drawable.honda200433},
            {R.drawable.lamborghini201631, R.drawable.lamborghini201632, R.drawable.lamborghini201633},
            {R.drawable.mazda202031, R.drawable.mazda202032, R.drawable.mazda202033},
            {R.drawable.mazda201031, R.drawable.mazda201032, R.drawable.mazda201033},
            {R.drawable.mazda201831, R.drawable.mazda201832, R.drawable.mazda201833},
            {R.drawable.toyota201231, R.drawable.toyota201232, R.drawable.toyota201233},
            {R.drawable.toyota201731, R.drawable.toyota201732, R.drawable.toyota201733}
    };

    static String[] carCategorys = {
            "Electric", "Electric", "Electric", "Electric", "Electric", "Electric", "Electric", "Electric", "Electric", "Electric", "Electric",
            "Hybrid", "Hybrid", "Hybrid", "Hybrid", "Hybrid", "Hybrid", "Hybrid", "Hybrid", "Hybrid", "Hybrid",
            "Petrol", "Petrol", "Petrol", "Petrol", "Petrol", "Petrol", "Petrol", "Petrol", "Petrol", "Petrol"
    };

    public static int[] getTopThreeViewedCars() { //this function searches though the cars array 3 times finding the top 3 most view cars and returns their ids
        int[] cars = carViews.clone();
        int first = getIndexOfMostViewedCar(cars, 0);
        cars[first] = -1;
        int second = getIndexOfMostViewedCar(cars, 1);
        cars[second] = -1;
        int third = getIndexOfMostViewedCar(cars, 2);
        cars[third] = -1;
        return new int[]{first,second,third};
    }

    private static int getIndexOfMostViewedCar( int[] cars , int _default) //this is where it can iterate through the views array and find the most viewed car
    {
        int largest = _default;
        for ( int i = 1; i < cars.length; i++ ) if ( cars[i] > cars[largest] ) largest = i;
        return largest; // position of the first largest found
    }

    public static ArrayList<Car> generateData() { //this iterates though the whole cars database and returns the full list of cars
        final ArrayList<Car> cars = new ArrayList<Car>();
        for (int i = 0; i < carNames.length; i++) {
            cars.add(new Car(carIds[i], carNames[i], carCategorys[i], carImages[i], carYears[i], carMakes[i], carDescriptions[i]));
        }
        return cars;
    }

    public static ArrayList<Car> generateDataSearch(String search) { //this function allows the list to be filtered by a string
        ArrayList<Car> cars = new ArrayList<Car>();
        if (search.toLowerCase().equals("electric")) { //if the electric category is selected
            for (int i = 0; i < carNames.length; i++) {
                if(carCategorys[i].toLowerCase().equals(search)) cars.add(new Car(carIds[i], carNames[i], carCategorys[i], carImages[i], carYears[i], carMakes[i], carDescriptions[i]));
            }
        }
        else if (search.toLowerCase().equals("hybrid")) { //if the hybrid category is selected
            for (int i = 0; i < carNames.length; i++) {
                if(carCategorys[i].toLowerCase().equals(search)) cars.add(new Car(carIds[i], carNames[i], carCategorys[i], carImages[i], carYears[i], carMakes[i], carDescriptions[i]));
            }
        }
        else if (search.toLowerCase().equals("petrol")) { //if the petrol category is selected
            for (int i = 0; i < carNames.length; i++) {
                if(carCategorys[i].toLowerCase().equals(search)) cars.add(new Car(carIds[i], carNames[i], carCategorys[i], carImages[i], carYears[i], carMakes[i], carDescriptions[i]));
            }
        }
        else { //if no category is triggered, then check each cars details and check if the search string is found anywhere, if so add that car to the list.
            for (int i = 0; i < carNames.length; i++) {
                if(carNames[i].toLowerCase().contains(search.toLowerCase())) cars.add(new Car(carIds[i], carNames[i], carCategorys[i], carImages[i], carYears[i], carMakes[i], carDescriptions[i]));
                else if(carMakes[i].toLowerCase().contains(search.toLowerCase())) cars.add(new Car(carIds[i], carNames[i], carCategorys[i], carImages[i], carYears[i], carMakes[i], carDescriptions[i]));
                else if(carYears[i].toLowerCase().contains(search.toLowerCase())) cars.add(new Car(carIds[i], carNames[i], carCategorys[i], carImages[i], carYears[i], carMakes[i], carDescriptions[i]));
            }
        }
        return cars;
    }
}